spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ExamManagement?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
jwt.secret-key: RikkeiAcademy
jwt.expired: 864000000
server:
  port: 8888
springdoc:
  api-docs:
    path: /api-docs # /api-docs endpoint custom path
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui # Custom Swagger-ui path.